
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Jun  1 2025 22:41:18 EEST (Jun  1 2025 19:41:18 UTC)

// Verification Directory fv/CarrySkipReg 

module CarrySkip_n4_m4(A, B, Cin, Outp, Cout);
  input [15:0] A, B;
  input Cin;
  output [15:0] Outp;
  output Cout;
  wire [15:0] A, B;
  wire Cin;
  wire [15:0] Outp;
  wire Cout;
  wire UNCONNECTED, n_0, n_1, n_2, n_4, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_23, n_24, n_25, n_30, n_31;
  wire n_32, n_34, n_35, n_36, n_37, n_42, n_43, n_44;
  wire n_45, n_47, n_50, n_51, n_52, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_65;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_88, n_90, n_91, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_116, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_126, n_127, n_128, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_204, n_205, n_206, n_207;
  wire n_209, n_210, n_211, n_216, n_217, n_220, n_221, n_224;
  wire n_225, n_226, n_262, n_264, n_265, n_266, n_267, n_269;
  wire n_272, n_273, n_274, n_278, n_280, n_282, n_283, n_287;
  wire n_288, n_291, n_293, n_294, n_299, n_300, n_306, n_308;
  wire n_310, n_312, n_314, n_315, n_316, n_317, n_318, n_319;
  wire n_320, n_322;
  OAI21X4 g6648__2398(.A0 (n_62), .A1 (n_198), .B0 (n_226), .Y
       (Outp[14]));
  MXI2X1 g6649__5107(.A (n_57), .B (n_61), .S0 (n_224), .Y (Outp[13]));
  CLKMX2X3 g6650__6260(.A (n_299), .B (n_300), .S0 (n_225), .Y
       (Outp[8]));
  OAI22X4 g6653__4319(.A0 (n_154), .A1 (n_217), .B0 (n_17), .B1
       (n_163), .Y (n_224));
  NOR2X4 g6654__8428(.A (n_167), .B (n_220), .Y (n_225));
  OAI21X2 g6655__5526(.A0 (n_184), .A1 (n_4), .B0 (n_221), .Y
       (Outp[12]));
  XNOR2X1 g6656__6783(.A (n_105), .B (n_217), .Y (Outp[4]));
  OAI21X2 g6657__3680(.A0 (n_201), .A1 (n_209), .B0 (n_4), .Y (n_221));
  NOR2X4 g6658__1617(.A (n_154), .B (n_217), .Y (n_220));
  OAI21X2 g6659__2802(.A0 (n_211), .A1 (n_207), .B0 (n_216), .Y
       (Outp[10]));
  CLKXOR2X1 g6660__1705(.A (n_104), .B (n_211), .Y (Outp[6]));
  NAND2X2 g6662__8246(.A (n_210), .B (n_205), .Y (Cout));
  NOR2X4 g6663__7098(.A (n_84), .B (n_200), .Y (n_217));
  OAI21X4 g6664__6131(.A0 (n_202), .A1 (n_194), .B0 (n_206), .Y
       (Outp[15]));
  MXI2X1 g6665__1881(.A (n_189), .B (n_58), .S0 (n_192), .Y (Outp[9]));
  CLKMX2X3 g6666__5115(.A (n_196), .B (n_204), .S0 (n_190), .Y
       (Outp[11]));
  AOI21X2 g6667__7482(.A0 (n_116), .A1 (n_278), .B0 (n_113), .Y
       (n_210));
  NOR2X6 g6668__4733(.A (n_81), .B (n_192), .Y (n_211));
  AOI2BB1X4 g6669__6161(.A0N (n_265), .A1N (n_186), .B0 (n_120), .Y
       (n_209));
  CLKXOR2X1 g6670__9315(.A (n_18), .B (n_4), .Y (Outp[7]));
  XNOR2X2 g6671__9945(.A (n_107), .B (n_199), .Y (n_207));
  NAND2X6 g6672__2883(.A (n_202), .B (n_195), .Y (n_206));
  NAND2X4 g6673__2346(.A (n_144), .B (n_202), .Y (n_205));
  MXI2X1 g6674__1666(.A (n_265), .B (n_264), .S0 (n_191), .Y (n_204));
  XNOR2X1 g6675__7410(.A (n_103), .B (n_193), .Y (Outp[3]));
  AOI21X2 g6676__6417(.A0 (n_138), .A1 (n_59), .B0 (n_287), .Y (n_201));
  NOR2BX4 g6677__5477(.AN (n_103), .B (n_193), .Y (n_200));
  OAI21X4 g6678__2398(.A0 (n_25), .A1 (n_170), .B0 (n_272), .Y (n_199));
  OAI21X4 g6679__5107(.A0 (n_149), .A1 (n_185), .B0 (n_56), .Y (n_202));
  XNOR2X2 g6681__6260(.A (n_283), .B (n_183), .Y (n_198));
  OAI22X4 g6682__4319(.A0 (n_283), .A1 (n_60), .B0 (n_282), .B1
       (n_188), .Y (n_197));
  CLKMX2X3 g6684__8428(.A (n_265), .B (n_264), .S0 (n_186), .Y (n_196));
  CLKMX2X3 g6685__5526(.A (n_47), .B (n_116), .S0 (n_182), .Y (n_195));
  CLKMX2X3 g6686__6783(.A (n_47), .B (n_116), .S0 (n_187), .Y (n_194));
  OAI21X4 g6687__3680(.A0 (n_43), .A1 (n_159), .B0 (n_42), .Y (n_191));
  AOI21X4 g6688__1617(.A0 (n_111), .A1 (n_164), .B0 (n_82), .Y (n_193));
  NOR2X6 g6689__2802(.A (n_106), .B (n_185), .Y (n_192));
  AOI2BB1X4 g6692__5122(.A0N (n_124), .A1N (n_181), .B0 (n_145), .Y
       (n_190));
  CLKINVX4 g6693(.A (n_60), .Y (n_188));
  NAND2X4 g6696__8246(.A (n_9), .B (n_176), .Y (n_187));
  NOR2X2 g6697__7098(.A (n_75), .B (n_174), .Y (n_186));
  AND2X6 g6698__6131(.A (n_80), .B (n_181), .Y (n_185));
  NOR2X4 g6702__1881(.A (n_171), .B (n_180), .Y (n_183));
  AOI2BB1X4 g6703__5115(.A0N (n_131), .A1N (n_51), .B0 (n_175), .Y
       (n_182));
  OAI21X4 g6704__7482(.A0 (n_294), .A1 (n_156), .B0 (n_45), .Y (n_180));
  AOI21X4 g6705__4733(.A0 (n_293), .A1 (n_155), .B0 (n_36), .Y (n_179));
  NOR2X4 g6706__6161(.A (n_76), .B (n_168), .Y (n_178));
  AOI21X4 g6707__9315(.A0 (n_322), .A1 (n_164), .B0 (n_150), .Y
       (n_181));
  OAI21X2 g6708__9945(.A0 (n_310), .A1 (n_162), .B0 (n_262), .Y
       (n_177));
  CLKINVX4 g6709(.A (n_175), .Y (n_176));
  XNOR2X1 g6711__2883(.A (n_107), .B (n_159), .Y (n_173));
  CLKXOR2X1 g6712__2346(.A (n_111), .B (n_164), .Y (Outp[2]));
  NAND2X6 g6713__1666(.A (n_161), .B (n_169), .Y (n_175));
  AOI21X4 g6714__7410(.A0 (n_274), .A1 (n_157), .B0 (n_43), .Y (n_174));
  OAI21X4 g6716__6417(.A0 (n_36), .A1 (n_148), .B0 (n_282), .Y (n_169));
  NOR2X6 g6717__5477(.A (n_294), .B (n_158), .Y (n_171));
  AOI21X4 g6718__2398(.A0 (n_300), .A1 (n_141), .B0 (n_76), .Y (n_170));
  OAI2BB1X2 g6720__5107(.A0N (n_18), .A1N (n_145), .B0 (n_139), .Y
       (n_167));
  AOI21X4 g6721__6260(.A0 (n_11), .A1 (n_140), .B0 (n_299), .Y (n_168));
  OAI21X2 g6722__4319(.A0 (n_119), .A1 (n_147), .B0 (n_138), .Y
       (n_166));
  AOI21X4 g6723__8428(.A0 (n_137), .A1 (n_146), .B0 (n_142), .Y
       (n_165));
  AOI21X4 g6725__6783(.A0 (n_107), .A1 (n_54), .B0 (n_75), .Y (n_162));
  AOI21X4 g6726__3680(.A0 (n_75), .A1 (n_133), .B0 (n_70), .Y (n_161));
  NOR2X1 g6727__1617(.A (n_83), .B (n_151), .Y (n_160));
  OAI21X4 g6728__2802(.A0 (n_135), .A1 (n_112), .B0 (n_69), .Y (n_164));
  AOI21X4 g6729__1705(.A0 (n_273), .A1 (n_137), .B0 (n_37), .Y (n_158));
  OAI21X4 g6731__5122(.A0 (n_76), .A1 (n_12), .B0 (n_24), .Y (n_157));
  AOI21X4 g6732__8246(.A0 (n_127), .A1 (n_137), .B0 (n_55), .Y (n_156));
  OAI21X4 g6733__7098(.A0 (n_123), .A1 (n_136), .B0 (n_153), .Y
       (n_155));
  NOR2X6 g6734__6131(.A (n_291), .B (n_143), .Y (n_159));
  ADDHX1 g6736__1881(.A (Cin), .B (n_100), .CO (n_151), .S (Outp[0]));
  NAND2X4 g6737__5115(.A (n_105), .B (n_1), .Y (n_154));
  NOR2BX4 g6739__7482(.AN (n_105), .B (n_132), .Y (n_150));
  NAND2X2 g6740__4733(.A (n_300), .B (n_1), .Y (n_149));
  NOR2X8 g6741__6161(.A (n_294), .B (n_134), .Y (n_148));
  OR2X6 g6742__9315(.A (n_288), .B (n_138), .Y (n_153));
  NOR3X2 g6744__9945(.A (n_47), .B (n_131), .C (n_51), .Y (n_144));
  NOR2X6 g6745__2883(.A (n_126), .B (n_139), .Y (n_143));
  OAI21X4 g6746__2346(.A0 (n_42), .A1 (n_310), .B0 (n_134), .Y (n_142));
  OAI2BB1X4 g6747__1666(.A0N (n_16), .A1N (n_44), .B0 (n_139), .Y
       (n_141));
  OAI21X4 g6748__7410(.A0 (n_78), .A1 (n_314), .B0 (n_18), .Y (n_140));
  OAI21X4 g6749__6417(.A0 (n_11), .A1 (n_123), .B0 (n_52), .Y (n_146));
  OAI21X4 g6750__5477(.A0 (n_80), .A1 (n_124), .B0 (n_50), .Y (n_145));
  CLKINVX4 g6751(.A (n_137), .Y (n_136));
  NOR2X6 g6752__2398(.A (n_83), .B (n_121), .Y (n_135));
  AOI21X4 g6755__5107(.A0 (n_78), .A1 (n_16), .B0 (n_0), .Y (n_139));
  AOI21X4 g6756__6260(.A0 (n_75), .A1 (n_108), .B0 (n_19), .Y (n_138));
  CLKAND2X12 g6757__4319(.A (n_107), .B (n_122), .Y (n_137));
  AOI21X4 g6760__8428(.A0 (n_82), .A1 (n_103), .B0 (n_84), .Y (n_132));
  NOR2X6 g6763__5526(.A (n_37), .B (n_128), .Y (n_134));
  CLKAND2X12 g6765__6783(.A (n_130), .B (n_122), .Y (n_133));
  NOR2X6 g6766__3680(.A (n_8), .B (n_102), .Y (n_130));
  NOR2BX4 g6768__2802(.AN (n_77), .B (n_110), .Y (n_128));
  AND2X2 g6769__1705(.A (n_76), .B (n_24), .Y (n_127));
  NAND2X4 g6770__5122(.A (n_300), .B (n_24), .Y (n_126));
  NAND2X2 g6771__8246(.A (n_269), .B (n_107), .Y (n_131));
  NOR2X4 g6774__7098(.A (n_30), .B (n_74), .Y (n_121));
  OR2X1 g6775__6131(.A (n_19), .B (n_288), .Y (n_120));
  NAND2X1 g6776__1881(.A (n_266), .B (n_107), .Y (n_119));
  OR2X6 g6778__7482(.A (n_106), .B (n_104), .Y (n_124));
  OR2X6 g6779__4733(.A (n_97), .B (n_109), .Y (n_123));
  NOR2X8 g6780__6161(.A (n_110), .B (n_267), .Y (n_122));
  ADDHX1 g6801__9315(.A (A[15]), .B (B[15]), .CO (n_113), .S (n_116));
  AOI22X4 g6803__9945(.A0 (A[1]), .A1 (n_34), .B0 (B[1]), .B1 (n_35),
       .Y (n_112));
  NAND2X4 g6804__2883(.A (n_318), .B (n_319), .Y (n_111));
  NAND2X8 g6805__2346(.A (n_79), .B (n_72), .Y (n_110));
  NAND2X6 g6807__1666(.A (n_98), .B (n_99), .Y (n_109));
  NOR2X8 g6808__7410(.A (n_77), .B (n_73), .Y (n_108));
  NOR2X6 g6809__6417(.A (n_96), .B (n_75), .Y (n_107));
  CLKXOR2X1 g6810__5477(.A (A[0]), .B (B[0]), .Y (n_100));
  NOR2X6 g6811__2398(.A (n_90), .B (n_88), .Y (n_106));
  NAND2X6 g6812__5107(.A (n_315), .B (n_320), .Y (n_105));
  NOR2X6 g6813__6260(.A (n_85), .B (n_91), .Y (n_104));
  NAND2X6 g6814__4319(.A (n_316), .B (n_317), .Y (n_103));
  NOR2X6 g6815__8428(.A (n_71), .B (n_2), .Y (n_102));
  NOR2X6 g6816__5526(.A (n_68), .B (n_86), .Y (n_101));
  NOR2X2 g6819__6783(.A (n_20), .B (A[8]), .Y (n_97));
  NOR2X2 g6820__3680(.A (B[10]), .B (A[10]), .Y (n_96));
  NOR2X6 g6821__1617(.A (A[7]), .B (n_308), .Y (n_95));
  OR2X2 g6823__2802(.A (B[13]), .B (A[13]), .Y (n_94));
  NOR2X4 g6826__8246(.A (A[6]), .B (n_63), .Y (n_91));
  NOR2X6 g6829__7098(.A (B[5]), .B (n_14), .Y (n_90));
  NOR2X6 g6831__1881(.A (A[5]), .B (n_65), .Y (n_88));
  NOR2X6 g6833__7482(.A (A[8]), .B (n_21), .Y (n_86));
  NOR2X4 g6834__4733(.A (B[6]), .B (n_67), .Y (n_85));
  OR2X6 g6836__6161(.A (B[9]), .B (A[9]), .Y (n_99));
  NAND2X6 g6837__9315(.A (B[9]), .B (A[9]), .Y (n_98));
  NOR2X4 g6840__9945(.A (B[0]), .B (A[0]), .Y (n_74));
  NOR2X8 g6841__2883(.A (B[11]), .B (n_280), .Y (n_73));
  OR2X4 g6842__2346(.A (B[12]), .B (A[12]), .Y (n_72));
  NOR2X4 g6843__1666(.A (B[14]), .B (n_32), .Y (n_71));
  AND2X1 g6844__7410(.A (A[14]), .B (B[14]), .Y (n_70));
  NAND2X1 g6845__6417(.A (B[1]), .B (A[1]), .Y (n_69));
  NOR2X4 g6846__5477(.A (n_20), .B (n_31), .Y (n_68));
  AND2X2 g6847__2398(.A (A[3]), .B (B[3]), .Y (n_84));
  CLKAND2X3 g6848__5107(.A (B[0]), .B (A[0]), .Y (n_83));
  CLKAND2X6 g6850__4319(.A (B[5]), .B (A[5]), .Y (n_81));
  NAND2X1 g6851__8428(.A (B[4]), .B (A[4]), .Y (n_80));
  CLKAND2X6 g6856__6783(.A (A[11]), .B (B[11]), .Y (n_77));
  CLKAND2X3 g6857__3680(.A (B[8]), .B (A[8]), .Y (n_76));
  AND2X6 g6858__1617(.A (B[10]), .B (A[10]), .Y (n_75));
  CLKINVX4 g6863(.A (A[6]), .Y (n_67));
  CLKINVX6 fopt6891(.A (A[7]), .Y (n_23));
  CLKINVX6 fopt6893(.A (n_20), .Y (n_21));
  CLKINVX6 fopt5(.A (n_7), .Y (n_16));
  CLKINVX4 fopt6904(.A (A[5]), .Y (n_14));
  NOR2X4 g2__1705(.A (n_13), .B (n_101), .Y (n_12));
  NOR2BX2 g3__5122(.AN (n_23), .B (n_95), .Y (n_13));
  NOR2X6 g6908__8246(.A (n_10), .B (n_95), .Y (n_7));
  NOR2X6 g6909__7098(.A (B[7]), .B (n_23), .Y (n_10));
  NAND3X2 g6910__6131(.A (n_107), .B (n_291), .C (n_133), .Y (n_9));
  AOI21X4 g6912__1881(.A0 (n_269), .A1 (n_76), .B0 (n_273), .Y (n_52));
  NAND2X6 g6914__5115(.A (n_306), .B (n_179), .Y (n_60));
  NAND2BX4 g6917__4733(.AN (n_78), .B (n_190), .Y (n_4));
  NOR2BX4 g6920__6161(.AN (B[14]), .B (A[14]), .Y (n_2));
  NOR2BX2 g6921__9315(.AN (n_16), .B (n_124), .Y (n_1));
  NOR2BX2 g6922__9945(.AN (B[7]), .B (n_23), .Y (n_0));
  BUFX12 fopt6924(.A (B[8]), .Y (n_20));
  INVX2 g6926(.A (A[8]), .Y (n_31));
  INVX2 g6938(.A (Cin), .Y (n_30));
  INVX2 g6940(.A (B[1]), .Y (n_34));
  INVX2 g6942(.A (A[1]), .Y (n_35));
  NAND2X4 g6944__2883(.A (B[13]), .B (A[13]), .Y (n_45));
  INVX2 g6946(.A (A[14]), .Y (n_32));
  INVX1 g6956(.A (n_116), .Y (n_47));
  INVX2 g6962(.A (n_45), .Y (n_36));
  INVX2 g6964(.A (n_79), .Y (n_37));
  INVX1 g6968(.A (n_75), .Y (n_42));
  INVX2 g6974(.A (n_107), .Y (n_43));
  INVX2 g6976(.A (n_133), .Y (n_51));
  INVX2 g6978(.A (n_314), .Y (n_50));
  INVX1 fopt6980(.A (n_18), .Y (n_17));
  NAND2X4 g6986__7410(.A (n_274), .B (n_123), .Y (n_54));
  INVX1 fopt6988(.A (n_24), .Y (n_25));
  INVX1 g6990(.A (n_104), .Y (n_44));
  CLKXOR2X1 g6992__6417(.A (n_112), .B (n_160), .Y (Outp[1]));
  INVX1 g6994(.A (n_168), .Y (n_56));
  XNOR2X1 g6996__5477(.A (n_294), .B (n_165), .Y (n_57));
  NAND2X2 g6998__2398(.A (n_264), .B (n_174), .Y (n_59));
  CLKXOR2X1 g7000__5107(.A (n_106), .B (n_185), .Y (Outp[5]));
  BUFX3 fopt7002(.A (n_16), .Y (n_18));
  XNOR2X1 g7008__6260(.A (n_293), .B (n_177), .Y (n_61));
  NAND2X6 g7012__4319(.A (n_62), .B (n_197), .Y (n_226));
  CLKINVX8 fopt3(.A (n_108), .Y (n_267));
  BUFX6 fopt7017(.A (n_99), .Y (n_269));
  CLKINVX6 fopt7019(.A (n_274), .Y (n_273));
  BUFX6 fopt4(.A (n_98), .Y (n_274));
  BUFX3 fopt7022(.A (n_187), .Y (n_278));
  BUFX6 fopt7023(.A (A[11]), .Y (n_280));
  BUFX6 fopt7031(.A (n_102), .Y (n_283));
  BUFX6 fopt7034(.A (n_110), .Y (n_288));
  CLKINVX6 fopt7035(.A (n_52), .Y (n_291));
  BUFX6 fopt7039(.A (n_8), .Y (n_294));
  CLKINVX8 fopt7045(.A (n_101), .Y (n_300));
  CLKINVX6 fopt7046(.A (n_171), .Y (n_306));
  CLKINVX6 fopt7047(.A (B[7]), .Y (n_308));
  BUFX6 fopt7050(.A (n_122), .Y (n_312));
  NAND2X6 g7052__8428(.A (n_45), .B (n_94), .Y (n_8));
  BUFX6 fopt7054(.A (n_77), .Y (n_19));
  ADDHX4 g7056__5526(.A (B[6]), .B (A[6]), .CO (n_78), .S
       (UNCONNECTED));
  NOR2BX4 g2(.AN (n_81), .B (n_104), .Y (n_314));
  NAND2BX4 g7059(.AN (B[4]), .B (A[4]), .Y (n_315));
  NAND2BX4 g7060(.AN (B[3]), .B (A[3]), .Y (n_316));
  NAND2BX4 g7061(.AN (A[3]), .B (B[3]), .Y (n_317));
  NAND2BX4 g7062(.AN (B[2]), .B (A[2]), .Y (n_318));
  NAND2BX4 g7063(.AN (A[2]), .B (B[2]), .Y (n_319));
  NAND2BX4 g7064(.AN (A[4]), .B (B[4]), .Y (n_320));
  AND3X6 g7066(.A (n_103), .B (n_111), .C (n_105), .Y (n_322));
  INVX3 g7069(.A (B[5]), .Y (n_65));
  INVX3 g7071(.A (B[6]), .Y (n_63));
  AND2X1 g6849__7073(.A (A[2]), .B (B[2]), .Y (n_82));
  NAND2X4 g6852__7075(.A (B[12]), .B (A[12]), .Y (n_79));
  INVX1 fopt7077(.A (n_288), .Y (n_287));
  INVX1 fopt7079(.A (n_273), .Y (n_272));
  INVX3 g7081(.A (n_153), .Y (n_55));
  INVX2 g7083(.A (n_146), .Y (n_147));
  BUFX2 fopt7085(.A (n_266), .Y (n_264));
  INVX3 g7087(.A (n_0), .Y (n_11));
  INVX3 fopt7089(.A (n_109), .Y (n_24));
  XNOR2X1 g7058__7091(.A (n_287), .B (n_166), .Y (n_184));
  XNOR2X1 g6879__7093(.A (n_25), .B (n_170), .Y (n_58));
  INVX2 fopt7095(.A (n_283), .Y (n_282));
  INVX2 fopt7097(.A (n_267), .Y (n_266));
  BUFX2 fopt7099(.A (n_134), .Y (n_262));
  INVX3 fopt7101(.A (n_312), .Y (n_310));
  NOR2X1 g6724__7103(.A (n_78), .B (n_145), .Y (n_163));
  XNOR2X1 g6690__7105(.A (n_25), .B (n_178), .Y (n_189));
  INVX3 g7107(.A (n_225), .Y (n_62));
  NAND2X2 g6661__7109(.A (n_173), .B (n_211), .Y (n_216));
  INVX1 fopt7112(.A (n_294), .Y (n_293));
  INVX1 fopt7114(.A (n_300), .Y (n_299));
  INVX1 fopt7116(.A (n_264), .Y (n_265));
endmodule

module CarrySkipReg(A, B, Cin, clk, rst, Outp, Cout);
  input [15:0] A, B;
  input Cin, clk, rst;
  output [15:0] Outp;
  output Cout;
  wire [15:0] A, B;
  wire Cin, clk, rst;
  wire [15:0] Outp;
  wire Cout;
  wire [15:0] A_Q;
  wire [15:0] B_Q;
  wire [1:0] Cin_Q;
  wire [15:0] Outp_Q;
  wire [1:0] Cout_Q;
  wire n_0;
  CarrySkip_n4_m4 CSkip(.A (A_Q), .B (B_Q), .Cin (Cin_Q[1]), .Outp
       (Outp_Q), .Cout (Cout_Q[1]));
  DFFRHQX1 \Reg4_d_reg[15] (.RN (n_0), .CK (clk), .D (Outp_Q[15]), .Q
       (Outp[15]));
  DFFRHQX1 \Reg4_d_reg[14] (.RN (n_0), .CK (clk), .D (Outp_Q[14]), .Q
       (Outp[14]));
  DFFRHQX1 \Reg4_d_reg[12] (.RN (n_0), .CK (clk), .D (Outp_Q[12]), .Q
       (Outp[12]));
  DFFRHQX1 \Reg4_d_reg[8] (.RN (n_0), .CK (clk), .D (Outp_Q[8]), .Q
       (Outp[8]));
  DFFRHQX1 \Reg4_d_reg[0] (.RN (n_0), .CK (clk), .D (Outp_Q[0]), .Q
       (Outp[0]));
  DFFRHQX1 \Reg5_d_reg[1] (.RN (n_0), .CK (clk), .D (Cout_Q[1]), .Q
       (Cout));
  DFFRHQX1 \Reg4_d_reg[7] (.RN (n_0), .CK (clk), .D (Outp_Q[7]), .Q
       (Outp[7]));
  DFFRHQX1 \Reg4_d_reg[11] (.RN (n_0), .CK (clk), .D (Outp_Q[11]), .Q
       (Outp[11]));
  DFFRHQX1 \Reg4_d_reg[6] (.RN (n_0), .CK (clk), .D (Outp_Q[6]), .Q
       (Outp[6]));
  DFFRHQX1 \Reg4_d_reg[5] (.RN (n_0), .CK (clk), .D (Outp_Q[5]), .Q
       (Outp[5]));
  DFFRHQX1 \Reg4_d_reg[13] (.RN (n_0), .CK (clk), .D (Outp_Q[13]), .Q
       (Outp[13]));
  DFFRHQX1 \Reg4_d_reg[10] (.RN (n_0), .CK (clk), .D (Outp_Q[10]), .Q
       (Outp[10]));
  DFFRHQX1 \Reg4_d_reg[4] (.RN (n_0), .CK (clk), .D (Outp_Q[4]), .Q
       (Outp[4]));
  DFFRHQX1 \Reg4_d_reg[3] (.RN (n_0), .CK (clk), .D (Outp_Q[3]), .Q
       (Outp[3]));
  DFFRHQX1 \Reg4_d_reg[9] (.RN (n_0), .CK (clk), .D (Outp_Q[9]), .Q
       (Outp[9]));
  DFFRHQX1 \Reg4_d_reg[2] (.RN (n_0), .CK (clk), .D (Outp_Q[2]), .Q
       (Outp[2]));
  DFFRHQX1 \Reg4_d_reg[1] (.RN (n_0), .CK (clk), .D (Outp_Q[1]), .Q
       (Outp[1]));
  DFFRHQX4 \Reg1_d_reg[2] (.RN (n_0), .CK (clk), .D (A[2]), .Q
       (A_Q[2]));
  DFFRHQX4 \Reg2_d_reg[10] (.RN (n_0), .CK (clk), .D (B[10]), .Q
       (B_Q[10]));
  DFFRHQX4 \Reg2_d_reg[3] (.RN (n_0), .CK (clk), .D (B[3]), .Q
       (B_Q[3]));
  DFFRHQX4 \Reg2_d_reg[14] (.RN (n_0), .CK (clk), .D (B[14]), .Q
       (B_Q[14]));
  DFFRHQX4 \Reg1_d_reg[14] (.RN (n_0), .CK (clk), .D (A[14]), .Q
       (A_Q[14]));
  DFFRHQX4 \Reg1_d_reg[8] (.RN (n_0), .CK (clk), .D (A[8]), .Q
       (A_Q[8]));
  DFFRHQX4 \Reg2_d_reg[1] (.RN (n_0), .CK (clk), .D (B[1]), .Q
       (B_Q[1]));
  DFFRHQX4 \Reg1_d_reg[13] (.RN (n_0), .CK (clk), .D (A[13]), .Q
       (A_Q[13]));
  DFFRHQX4 \Reg1_d_reg[3] (.RN (n_0), .CK (clk), .D (A[3]), .Q
       (A_Q[3]));
  DFFRHQX4 \Reg1_d_reg[1] (.RN (n_0), .CK (clk), .D (A[1]), .Q
       (A_Q[1]));
  DFFRHQX4 \Reg1_d_reg[0] (.RN (n_0), .CK (clk), .D (A[0]), .Q
       (A_Q[0]));
  DFFRHQX1 \Reg2_d_reg[15] (.RN (n_0), .CK (clk), .D (B[15]), .Q
       (B_Q[15]));
  DFFRHQX4 \Reg1_d_reg[5] (.RN (n_0), .CK (clk), .D (A[5]), .Q
       (A_Q[5]));
  DFFRHQX4 \Reg2_d_reg[12] (.RN (n_0), .CK (clk), .D (B[12]), .Q
       (B_Q[12]));
  DFFRHQX4 \Reg2_d_reg[11] (.RN (n_0), .CK (clk), .D (B[11]), .Q
       (B_Q[11]));
  DFFRHQX4 \Reg2_d_reg[6] (.RN (n_0), .CK (clk), .D (B[6]), .Q
       (B_Q[6]));
  DFFRHQX4 \Reg1_d_reg[9] (.RN (n_0), .CK (clk), .D (A[9]), .Q
       (A_Q[9]));
  DFFRHQX4 \Reg2_d_reg[8] (.RN (n_0), .CK (clk), .D (B[8]), .Q
       (B_Q[8]));
  DFFRHQX4 \Reg2_d_reg[7] (.RN (n_0), .CK (clk), .D (B[7]), .Q
       (B_Q[7]));
  DFFRHQX4 \Reg1_d_reg[4] (.RN (n_0), .CK (clk), .D (A[4]), .Q
       (A_Q[4]));
  DFFRHQX4 \Reg2_d_reg[5] (.RN (n_0), .CK (clk), .D (B[5]), .Q
       (B_Q[5]));
  DFFRHQX4 \Reg2_d_reg[4] (.RN (n_0), .CK (clk), .D (B[4]), .Q
       (B_Q[4]));
  DFFRHQX4 \Reg2_d_reg[2] (.RN (n_0), .CK (clk), .D (B[2]), .Q
       (B_Q[2]));
  DFFRHQX4 \Reg3_d_reg[1] (.RN (n_0), .CK (clk), .D (Cin), .Q
       (Cin_Q[1]));
  DFFRHQX4 \Reg2_d_reg[0] (.RN (n_0), .CK (clk), .D (B[0]), .Q
       (B_Q[0]));
  DFFRHQX4 \Reg2_d_reg[13] (.RN (n_0), .CK (clk), .D (B[13]), .Q
       (B_Q[13]));
  DFFRHQX4 \Reg2_d_reg[9] (.RN (n_0), .CK (clk), .D (B[9]), .Q
       (B_Q[9]));
  DFFRHQX1 \Reg1_d_reg[15] (.RN (n_0), .CK (clk), .D (A[15]), .Q
       (A_Q[15]));
  DFFRHQX4 \Reg1_d_reg[12] (.RN (n_0), .CK (clk), .D (A[12]), .Q
       (A_Q[12]));
  DFFRHQX4 \Reg1_d_reg[11] (.RN (n_0), .CK (clk), .D (A[11]), .Q
       (A_Q[11]));
  DFFRHQX4 \Reg1_d_reg[10] (.RN (n_0), .CK (clk), .D (A[10]), .Q
       (A_Q[10]));
  DFFRHQX4 \Reg1_d_reg[7] (.RN (n_0), .CK (clk), .D (A[7]), .Q
       (A_Q[7]));
  DFFRHQX4 \Reg1_d_reg[6] (.RN (n_0), .CK (clk), .D (A[6]), .Q
       (A_Q[6]));
  INVXL g53(.A (rst), .Y (n_0));
endmodule

